### PR TITLE
Fix repository issue with duplicity

### PR DESCRIPTION
**Pull request by tersmitten**

### CODE REVIEW

**Comment by tersmitten** [comment]
Happy @mvdriel?

**Comment by mvdriel** [comment]
@tersmitten Very nice. Thanks!

**Comment by mmenozzi** [comment]
Hi guys, could you please tag a new stable version/release with this fix?

**Comment by tersmitten** [comment]
There's already one: https://github.com/Oefenweb/ansible-duplicity/releases

**Comment by mmenozzi** [comment]
Mmm strange I don’t see the 2.0.0 tag here: https://github.com/Oefenweb/ansible-duplicity/commit/a2f51d99f2c4ae3590920e6b42b7a5dae1a3f666

**Comment by tersmitten** [comment]
I May have been tagging before merge :-(

**Comment by tersmitten** [comment]
Fixed it for you: https://github.com/Oefenweb/ansible-duplicity/releases/tag/v2.0.1

**Comment by mmenozzi** [comment]
Thank you man!

**Comment by mmenozzi** [comment]
I cannot see the 2.0.1 version on ansible galaxy https://galaxy.ansible.com/oefenweb/duplicity. How often is updated there?

**Pull request merged**
